---
- name: Configure webservers with metricbeat
  hosts: webservers
  become: true
  tasks:
    # Downloads dkpg file from Metricbeat Website
    - name: Download Deb file from Metricbeat
      command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Installs .deb file onto webservers
    - name: deb file installation
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Copies Metricbeat config file
    - name: Copy metricbeat configuration file
      copy:
        src: /etc/ansible/files/metricbeat-configuration.yml
        dest: /etc/filebeat/metricbeat.yml

    # Metricbeat Enable & Setup
    - name: Enables Metricbeat
      command: metricbeat modules enable docker

    - name: Metricbeat Setup
      command: metricbeat setup

    - name: Metricbeat start
      command: sudo service metricbeat start